##################################################################################
## Expose Gitlab
##################################################################################
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: cicd
spec:
  type: NodePort
  ports:
  - name: gitlab-http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  - name: gitlab-https
    port: 443
    targetPort: 443
    nodePort: 30443
    protocol: TCP
  - port: 22
    targetPort: 22
    nodePort: 30022
    protocol: TCP
    name: ssh
  selector:
    app: gitlab
